version: "3.4"

services:
  jenkins:
    image: jenkins/jenkins:latest
    ports:
      - 9090:8080 
      - 50000:50000
    restart: always
    networks:
      - bridge
    volumes:
      - /var/lib/jenkins:/var/jenkins_home
      - /etc/localtime:/etc/localtime
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock://var/run/docker.sock
